server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cliente-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/clientes/**

        - id: produto-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/produtos/**

        - id: pedido-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/pedidos/**

        - id: estoque-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/estoque/**