server:
  port: 8084

spring:
  application:
    name: pagamento
  rabbitmq:
    #    host: localhost
    #    username: guest
    #    password: guest
    host: rabbitmq.tericcabrel.com
    username: admin
    password: MyStrong-P4ssw0rd$
    port: 5672
    virtual-host: /

